name: qrcode
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.5.0
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.0
  share: ^2.0.4
  table_calendar: ^3.0.0
  flutter_triple: ^3.0.0
  google_fonts: ^6.2.1
  drift: ^2.20.0
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  qr_flutter: ^4.1.0
  build_runner: ^2.0.0
  drift_dev: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/happyguy.png